mtime = 1599234242
[[pkgs]]
type = "github"
distrib = "e-json-encoder"
package = "e_json_encoder-1.0.4"
ext = "tar.gz"
sha256 = "89950c667da2ad5bb4268a12f7c6e36df082bc5b6d5aab7aedb830839b33646d"
url = "https://api.github.com/repos/jmt1/trial_pywharf2/releases/assets/24912774"

[pkgs.meta]
name = "e-json-encoder"
version = "1.0.4"
filetype = "sdist"
pyversion = ""
metadata_version = "2.1"
summary = "JSON Encoder allows you to recursively convert classes to json files and vice versa."
home_page = "https://github.com/embention/sw-Python_libs"
author = "Embention"
author_email = "alex.delgado@embention.com"
maintainer = ""
maintainer_email = ""
license = "Proprietary"
description = "# JSON Encoder\n\nJSON Encoder allows you to recursively convert classes to json files and vice versa.\n\n### METHODS\n\n - to_dict()\n - dumps()\n - dump(output_file_path)\n - loads(input_file_path)"
keywords = ""
platform = "UNKNOWN"
classifiers = "Programming Language :: Python :: 3"
download_url = ""
comment = ""
md5_digest = "2cc08c816f0f454e26b767a26b8c3f99"
sha256_digest = "89950c667da2ad5bb4268a12f7c6e36df082bc5b6d5aab7aedb830839b33646d"
blake2_256_digest = "61b2d52662ed4317d9ccbf22f7c0230c89a9819fbc07656e298121fc884c9be9"
requires_python = ">=3.7"
description_content_type = "text/markdown"
":action" = "file_upload"
protocol_version = "1"
distrib = "e-json-encoder"
sha256 = "89950c667da2ad5bb4268a12f7c6e36df082bc5b6d5aab7aedb830839b33646d"
[[pkgs]]
type = "github"
distrib = "e-json-encoder"
package = "e_json_encoder-1.0.4-py3-none-any"
ext = "whl"
sha256 = "67fccf17fe41810da894154d46076cd5554ea4a5a53f87193563ac64f7d5bb43"
url = "https://api.github.com/repos/jmt1/trial_pywharf2/releases/assets/24912771"

[pkgs.meta]
name = "e-json-encoder"
version = "1.0.4"
filetype = "bdist_wheel"
pyversion = "py3"
metadata_version = "2.1"
summary = "JSON Encoder allows you to recursively convert classes to json files and vice versa."
home_page = "https://github.com/embention/sw-Python_libs"
author = "Embention"
author_email = "alex.delgado@embention.com"
maintainer = ""
maintainer_email = ""
license = "Proprietary"
description = "# JSON Encoder\n\nJSON Encoder allows you to recursively convert classes to json files and vice versa.\n\n### METHODS\n\n - to_dict()\n - dumps()\n - dump(output_file_path)\n - loads(input_file_path)\n\n"
keywords = ""
platform = "UNKNOWN"
classifiers = "Programming Language :: Python :: 3"
download_url = ""
comment = ""
md5_digest = "5edc75a7be5a61a35a10459791528f22"
sha256_digest = "67fccf17fe41810da894154d46076cd5554ea4a5a53f87193563ac64f7d5bb43"
blake2_256_digest = "6e339283b1ee35c3be6938ee06fecebb1d15ca1e1469d9bc0f1e36e7af8201af"
requires_python = ">=3.7"
description_content_type = "text/markdown"
":action" = "file_upload"
protocol_version = "1"
distrib = "e-json-encoder"
sha256 = "67fccf17fe41810da894154d46076cd5554ea4a5a53f87193563ac64f7d5bb43"
[[pkgs]]
type = "github"
distrib = "e-json-encoder"
package = "E_JSON_Encoder-1.0.2-py3-none-any"
ext = "whl"
sha256 = "dde57f7d291a33dfd3071daa58ebc07f418c37fc2193a246297b35a6a8ec3f0f"
url = "https://api.github.com/repos/jmt1/trial_pywharf2/releases/assets/24836005"

[pkgs.meta]
name = "E-JSON-Encoder"
version = "1.0.2"
filetype = "bdist_wheel"
pyversion = "py3"
metadata_version = "2.1"
summary = "JSON Encoder allows you to recursively convert classes to json files and vice versa."
home_page = "https://github.com/embention/sw-Python_libs"
author = "Embention"
author_email = "alex.delgado@embention.com"
maintainer = ""
maintainer_email = ""
license = "Proprietary"
description = "# JSON Encoder\n\nJSON Encoder allows you to recursively convert classes to json files and vice versa.\n\n### METHODS\n\n - to_dict()\n - dumps()\n - dump(output_file_path)\n - loads(input_file_path)\n\n"
keywords = ""
platform = "UNKNOWN"
classifiers = "Programming Language :: Python :: 3"
download_url = ""
comment = ""
md5_digest = "20d57d3513ee97444062ab346f267075"
sha256_digest = "dde57f7d291a33dfd3071daa58ebc07f418c37fc2193a246297b35a6a8ec3f0f"
blake2_256_digest = "b0a6742e9d7d3bd46b606fbb136cbe0f6fc15264adf558572a401fece0e52380"
requires_python = ">=3.7"
description_content_type = "text/markdown"
":action" = "file_upload"
protocol_version = "1"
distrib = "e-json-encoder"
sha256 = "dde57f7d291a33dfd3071daa58ebc07f418c37fc2193a246297b35a6a8ec3f0f"
[[pkgs]]
type = "github"
distrib = "e-json-encoder"
package = "E_JSON_Encoder-1.0.0"
ext = "tar.gz"
sha256 = "4660e0a8c9c1707e20f7fef98262054b1fd6648fe1f17e809395059652b50062"
url = "https://api.github.com/repos/jmt1/trial_pywharf2/releases/assets/24835526"

[pkgs.meta]
name = "E-JSON-Encoder"
version = "1.0.0"
filetype = "sdist"
pyversion = ""
metadata_version = "2.1"
summary = "JSON Encoder allows you to recursively convert classes to json files and vice versa."
home_page = "https://github.com/embention/sw-Python_libs"
author = "Embention"
author_email = "alex.delgado@embention.com"
maintainer = ""
maintainer_email = ""
license = "Proprietary"
description = "# JSON Encoder\n\nJSON Encoder allows you to recursively convert classes to json files and vice versa.\n\n### METHODS\n\n - to_dict()\n - dumps()\n - dump(output_file_path)\n - loads(input_file_path)"
keywords = ""
platform = "UNKNOWN"
classifiers = "Programming Language :: Python :: 3"
download_url = ""
comment = ""
md5_digest = "bd24a0bf629d6eff2c3ab9c009c18c53"
sha256_digest = "4660e0a8c9c1707e20f7fef98262054b1fd6648fe1f17e809395059652b50062"
blake2_256_digest = "8fd50a8b6a0759b16c83636e0824037f09dc33b0650ee2e2474a4a1d84be5606"
requires_python = ">=3.7"
description_content_type = "text/markdown"
":action" = "file_upload"
protocol_version = "1"
distrib = "e-json-encoder"
sha256 = "4660e0a8c9c1707e20f7fef98262054b1fd6648fe1f17e809395059652b50062"
[[pkgs]]
type = "github"
distrib = "e-json-encoder"
package = "E_JSON_Encoder-1.0.0-py3-none-any"
ext = "whl"
sha256 = "4b8aafdb7d484c4277ea088ace1e147c5b26dec94ea0eab8faabaff21309a0ad"
url = "https://api.github.com/repos/jmt1/trial_pywharf2/releases/assets/24835524"

[pkgs.meta]
name = "E-JSON-Encoder"
version = "1.0.0"
filetype = "bdist_wheel"
pyversion = "py3"
metadata_version = "2.1"
summary = "JSON Encoder allows you to recursively convert classes to json files and vice versa."
home_page = "https://github.com/embention/sw-Python_libs"
author = "Embention"
author_email = "alex.delgado@embention.com"
maintainer = ""
maintainer_email = ""
license = "Proprietary"
description = "# JSON Encoder\n\nJSON Encoder allows you to recursively convert classes to json files and vice versa.\n\n### METHODS\n\n - to_dict()\n - dumps()\n - dump(output_file_path)\n - loads(input_file_path)\n\n"
keywords = ""
platform = "UNKNOWN"
classifiers = "Programming Language :: Python :: 3"
download_url = ""
comment = ""
md5_digest = "2c4dfde1cac6beed3e94989d489dda2c"
sha256_digest = "4b8aafdb7d484c4277ea088ace1e147c5b26dec94ea0eab8faabaff21309a0ad"
blake2_256_digest = "80ebab733a5955a183adbfcc028397b6e7bae04c8f8fd3954904623c20922a1f"
requires_python = ">=3.7"
description_content_type = "text/markdown"
":action" = "file_upload"
protocol_version = "1"
distrib = "e-json-encoder"
sha256 = "4b8aafdb7d484c4277ea088ace1e147c5b26dec94ea0eab8faabaff21309a0ad"
[[pkgs]]
type = "github"
distrib = "e-exception-manager"
package = "E_Exception_Manager-1.0.14-py3-none-any"
ext = "whl"
sha256 = "10d7d472646b1fe9478393293606b27c20f5eca5dcc1c2b4b083f4ea9c2060e9"
url = "https://api.github.com/repos/jmt1/trial_pywharf2/releases/assets/24828341"

[pkgs.meta]
name = "E-Exception-Manager"
version = "1.0.14"
filetype = "bdist_wheel"
pyversion = "py3"
metadata_version = "2.1"
summary = "Exception Manager allows you to handle exceptions and print them to a file using a decorator."
home_page = "https://github.com/embention/sw-Python_libs"
author = "Embention"
author_email = "javier.martinez@embention.com"
maintainer = ""
maintainer_email = ""
license = "Proprietary"
description = "# &#128165;  &#128165; Exception Manager  &#128165;  &#128165;\n\n## What it is?\n\nException Manager allows you to handle any exception and print the information about it (Exception Type, Exception Message, Exception Traceback...) to a file using a decorator before the method.\n\n## Usage\n\nException Manager prints the exception information to a file.\nThe path of that file can be default or custom. For example:\n\n ```python\nExceptionManager()\n```\n\nIn main.py file the default path will be \"main\" + \"_error.txt\" == **main_error.txt**\n\nOr user can define a `custom_path`:\n\n```python\nExceptionManager(custom_path)\n```\n\n#### Exception Manager can be used in two different ways:\n\n 1. Calling the decorator function with a default return value (@return_on_failure(value)).\n\n ```python\n    @return_on_failure([])\n    def function_name():\n        # function_body (without try/except)\n        test_list = ['A', 'B', 'C']\n        return test_list\n```\nIn this case, if exception occurs in the function_body, the returned value is `[]`. Try/except is not necessary in this example.\n\n 2. Calling `ExceptionManager(path).add_exception(error)` function from try/except in the code.\n\n ```python\n    def function_name():\n        # function_body (with try/except)\n        b = 0\n        try:\n            a = 1\n            if b > 3:\n                a = b\n        except Exception as error:\n            ExceptionManager().add_exception(error)\n        return a\n```\n\n\n"
keywords = ""
platform = "UNKNOWN"
classifiers = "Programming Language :: Python :: 3"
download_url = ""
comment = ""
md5_digest = "574c0d15d7f2503da5e6b36a65c1eddb"
sha256_digest = "10d7d472646b1fe9478393293606b27c20f5eca5dcc1c2b4b083f4ea9c2060e9"
blake2_256_digest = "7a5c91be678541a60bf851953c7c66ba407179b42e72bc1fb1760f1c7509ab9d"
requires_python = ">=3.7"
description_content_type = "text/markdown"
":action" = "file_upload"
protocol_version = "1"
distrib = "e-exception-manager"
sha256 = "10d7d472646b1fe9478393293606b27c20f5eca5dcc1c2b4b083f4ea9c2060e9"
