name: update-index
on:
  push:
  schedule:
    - cron: "* * * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Split owner/repo
        run: |
          echo "::set-env name=OWNER::$(cut -d/ -f1 <<< ${{ github.repository }})"
          echo "::set-env name=REPO::$(cut -d/ -f2 <<< ${{ github.repository }})"
      - name: Update index.
        uses: docker://pywharf/pywharf:0.2.0
        with:
          args: >-
            update_index
            --type github
            --name ${{ env.REPO }}
            --secret ${{ github.token }}
            --owner ${{ env.OWNER }}
            --repo ${{ env.REPO }}
            --branch master
            --index_filename index.toml
